### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ranshalit** [Ark444/YateBTS_smssend#2]
Hi,

Is it actually sending sms from a phone connected to private BTS network (this YateBTS) ?
 Doesn't starting private BTS network just for sending sms will interfere others networks ?

Thx.

**Comment by trpyn** [comment]
Hello, 

Sms are sent from the device running yateBTS to any device you want, which is connected to the network. You can already send sms between phones using yate.

The BTS network won't interfere with other networks if you set it up properly (take a look at the subscribers section in the configuration files). However you'll have to select your private network instead of the one you're​ currently connected to.

Hope this helps,

ark

**Comment by ranshalit** [comment]
Hi ark,

I plan to use bladeRF.
As I understand there is a PC which is installed with YateBTS connected to bladeRF:
PC --- usb cable ---- bladeRF ~~~~ MS devices

So does it mean that  the PC is sending the SMS ? 
Doesn't is required a SIM card in PC or bladeRF?

Thx a lot  !

**Comment by trpyn** [comment]
The pc sends the sms, yes.
No it doesn't require a sim card in any of theses because they provide the network.
The MS device however does need one.

And by the way I've done it with the bladerf, it works pretty well :)

**Comment by ranshalit** [comment]
This sms sender capability /app is awesome.
I wander why it is not part of official yateBTS.

**Comment by trpyn** [comment]
Well I might make a pull request someday, but I'll need to finish it first ^^'
